#include "uart.h"

/**
 * @brief 
 * description: initialized the io pin
 */
void uart_io_init(void)
{
    *IOMUXC_SW_MUX_CTL_PAD_UART1_TX_DATA = IOMUXC_SW_MUX_CTL_PAD_UART1_TX_DATA_UART1_TX;
    *IOMUXC_SW_MUX_CTL_PAD_UART1_RX_DATA = IOMUXC_SW_MUX_CTL_PAD_UART1_RX_DATA_UART1_RX;

    *IOMUXC_SW_PAD_CTL_PAD_UART1_TX_DATA = IOMUXC_SW_PAD_CTL_PAD_UART1_TX_DATA_UART1_TX;
    *IOMUXC_SW_PAD_CTL_PAD_UART1_RX_DATA = IOMUXC_SW_PAD_CTL_PAD_UART1_RX_DATA_UART1_RX;
}